spring.application.name=bodega-api

# Datos de conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bodega_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' en la Fase 1; en la Fase 2 pasara a 'none' por Flyway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar temporalmente Flyway mientras mapeamos las entidades de la Fase 1
spring.flyway.enabled=false